### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by RickH64** [aecreations/clippings-tb#21]
Hello, 

I can't install the latest clippings plugin clippings-6.0.6-an+fx.xpi for Windows Thunderbird 60.0 (32-bit) (portable)
This is the error message:

This add-on could not be installed because it appears to be corrupt.

Can you please help me?

**Comment by aecreations** [comment]
Clippings 6.0.6 is not compatible with Thunderbird. Clippings 6 is compatible with Firefox Quantum only.

There is a new release of Clippings for Thunderbird that will be compatible with Thunderbird 60. When it is released, it will be announced on [the AE Creations blog](http://aecreations.blogspot.com/). Until then, you can try the latest beta release of Clippings for Thunderbird; more info available [here](http://aecreations.blogspot.com/search/label/beta+thunderbird).
