### ISSUE TITLE
Port to Thunderbird 78, part 3 - Initialize IndexedDB storage, and implement New Clipping dialog

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings-tb#45]
This is the third part of an attempt to port Clippings for Thunderbird to Thunderbird 78.  WindowListener API tutorial: https://github.com/thundernest/addon-developer-support/wiki/WindowListener-API:-Finalizing

1. Change minVersion in the MailExtension manifest to 78.0.
2. Initialize IndexedDB data storage from background script; use the same logic from Clippings/wx.
3. The context menu in the message compose window should show temporary dummy menu items to confirm Clippings UI integration.
4. Implement the New Clipping dialog, porting the UI from Clippings/wx.
5. The status bar icon should remain available, but is non-functional.
6. For now, no Clippings Manager, and no extension preferences dialog; they will be added later.
7. Copy over the `aeConst` object from Clippings/wx.

**Comment by RayCulp** [comment]
Glad to hear this is still being worked on. Has there been any news on whether TB will introduce support for customizing the context menu in the editor?

**Comment by aecreations** [comment]
@RayCulp - None that I've seen so far. Someone had filed a Bugzilla bug requesting this ability, but there hasn't been any movement on that: https://bugzilla.mozilla.org/show_bug.cgi?id=1630603

**Comment by aecreations** [comment]
Among many caveats, the New Clipping dialog is visually broken, and the "Save the source web page address" checkbox should be removed as it is not applicable to an email client. But it is now possible to create a new clipping, set a shortcut key or label for it, and even create a folder to put it in.
