### ISSUE TITLE
Clippings Manager doesn't save clipping edit

### ISSUE THREAD

**Issue by aecreations** [aecreations/clippings-tb#85]
Clippings 6.0b3+

A serious regression bug impacting Clippings Manager. **Must be fixed before 6.0rc1.** Not reproducible in Clippings for Firefox.

Steps to repro:
1. Open Clippings Manager
2. Click "New Clipping"
3. Enter content for the new clipping. Then, without clicking anywhere else, click the 'X' on the window title bar to close Clippings Manager (or, press CTRL+W)

Result:
The content that was entered for the new clipping is unsaved, and is lost.

Editing clipping or folder name doesn't appear to be affected.

**Comment by RayCulp** [comment]
This may sound heretical, but tbh I think programs that save stuff without me clicking a button like "Save" or "OK" are weird. I never really trust them and always go back to make sure whatever it was (content or settings) has been saved correctly. Maybe I'm a dying breed, but if all else were to fail, I would be able to live with an "OK" button. Just my two cents. <3

**Comment by aecreations** [comment]
Caused by the fix for issue #51.

**Comment by aecreations** [comment]
Issue not fixed, reopening.
